---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.6.3-openjdk-8}}

caches:
  - path: $HOME/.m2/repository

inputs:
  - name: source-code
  - name: pipeline
  - name: version

outputs:
  - name: build-output

run:
  path: pipeline/tasks/maven-test-and-package.sh