---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.3.9-jdk-8}

caches:
  - path: $HOME/.m2/repository

inputs:
  - name: source-code
  - name: pipeline
  - name: version

run:
  path: pipeline/tasks/maven-verify.sh